public class KeyMap {

    final static String[][] keys = new String[][]{
            {
                "esc",
                    "grave",
                    "tab",
                    "caps",
                    "lshift",
                    "lctrl"
            }, {
                "1",
            "q",
            "a",
            "z",
            "lwin"
    },
            {
                "f1",
                "2",
                    "w",
                    "s",
                    "x",
                    "alt"
            }, {
                "f2",
            "3",
            "e",
            "d",
            "c",
            "space"
    },
            {
                "f3",
                    "4",
                    "f",
                    "v",
                    "space"
            },
            {
                "f4",
                    "5",
                    "t",
                    "g",
                    "b",
                    "space"
            },
            {
                "f4",
                    "5",
                    "t",
                    "g",
                    "b",
                    "space"
            },
            {
                "f5",
                    "6",
                    "y",
                    "h",
                    "n",
                    "space"
            }, {
            "f6",
            "7",
            "u",
            "j",
            "m",
            "space"
    },
            {
                    "f7",
                    "8",
                    "i",
                    "j",
                    "n",
                    "space",
            },
            {
                "f8",
                    "9",
                    "o",
                    "k",
                    "m",
                    "space"
            },
            {
                "0",
                    "p",
                    "l",
                    "comma",
                    "space"
            },
            {
                "f9",
                    "minus",
                    "lbrace",
                    "colon",
                    "dot",
                    "ralt"
            },
            {
                "f10",
                    "equal",
                    "rbrace",
                    "quote",
                    "slash",
                    "rwin"
            },
            {
                "f11",
                    "bspace",
                    "bslash",
                    "enter",
                    "rshift",
                    "rmenu"
            },
            {
                "f12",
                    "bspace",
                    "bslash",
                    "enter",
                    "rshift",
                    "rctrl"
            },
            {
                "prtscn",
                    "ins",
                    "del",
                    "left"
            },
            {
                "scroll",
                    "home",
                    "end",
                    "up",
                    "down"
            },
            {
                "pause",
                    "pgup",
                    "pgdn",
                    "right"
            },
            {
                "stop",
                    "numlock",
                    "num7",
                    "num4",
                    "num1",
                    "num0"
            },
            {
                "prev",
                    "numslash",
                    "num8",
                    "num5",
                    "num2",
                    "num0"
            },
            {
                "play",
                    "numstar",
                    "num9",
                    "num6",
                    "num3",
                    "numdot"
            },
            {
                "next",
                    "numminus",
                    "numplus",
                    "numenter"
            }
    };

}
